services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    image: star-burger-front-prod:latest
    restart: unless-stopped
    volumes:
      - ./bundles:/app/bundles

  web:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    image: star-burger-backend-prod:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      node:
        condition: service_started
    volumes:
      - .env:/app/.env:ro
      - ./assets:/app/assets
      - ./bundles:/app/bundles
      - ./media:/app/media
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --access-logfile -
      --error-logfile -
      --timeout 60
    expose:
      - "8000"

volumes:
  postgres_data:
