services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    image: star-burger-front-prod:latest
    restart: no
    volumes:
      - ./bundles:/app/bundles

  web:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
      args:
        SECRET_KEY: ${SECRET_KEY:-default-secret-key}
    image: star-burger-backend-prod:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - node
    volumes:
      - .env:/app/.env:ro
      - /opt/star_burger/assets:/app/assets
      - /opt/star_burger/bundles:/app/bundles
      - /opt/star_burger/media:/app/media
      - /opt/star_burger/staticfiles:/app/staticfiles
    command: >
      gunicorn star_burger.wsgi:application
      --bind 0.0.0.0:8080
      --workers 3
      --access-logfile -
      --error-logfile -
      --timeout 60
    ports:
      - "8080:8080"

volumes:
  postgres_data:
